project:
  type: website 
website:
  title: "BiosimWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: RunSBWPupaeSamplingDates.qmd
        text: SBW 
      - href: RunSpongyMothSamplingDates.qmd
        text: Spongy Moth

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

