project:
  type: website 
website:
  title: "BiosimWebsite"
  navbar:
    left:
      - href: RunSpongyMothSamplingDates.qmd
        text: Spongy Moth
      - href: RunSBWSamplingDates.qmd
        text: SBW (coming soon)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

